use serde::{Deserialize, Serialize};

/// Quant analytics, reward and risk scores for an ETF composite ticker.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct EtfGlobalAnalytics {
    pub composite_ticker: Option<String>,
    pub effective_date: Option<String>,
    pub processed_date: Option<String>,
    pub quant_composite_behavioral: Option<f64>,
    pub quant_composite_fundamental: Option<f64>,
    pub quant_composite_global: Option<f64>,
    pub quant_composite_quality: Option<f64>,
    pub quant_composite_sentiment: Option<f64>,
    pub quant_composite_technical: Option<f64>,
    pub quant_fundamental_div: Option<f64>,
    pub quant_fundamental_pb: Option<f64>,
    pub quant_fundamental_pcf: Option<f64>,
    pub quant_fundamental_pe: Option<f64>,
    pub quant_global_country: Option<f64>,
    pub quant_global_sector: Option<f64>,
    pub quant_grade: Option<String>,
    pub quant_quality_diversification: Option<f64>,
    pub quant_quality_firm: Option<f64>,
    pub quant_quality_liquidity: Option<f64>,
    pub quant_sentiment_iv: Option<f64>,
    pub quant_sentiment_pc: Option<f64>,
    pub quant_sentiment_si: Option<f64>,
    pub quant_technical_it: Option<f64>,
    pub quant_technical_lt: Option<f64>,
    pub quant_technical_st: Option<f64>,
    pub quant_total_score: Option<f64>,
    pub reward_score: Option<f64>,
    pub risk_country: Option<f64>,
    pub risk_deviation: Option<f64>,
    pub risk_efficiency: Option<f64>,
    pub risk_liquidity: Option<f64>,
    pub risk_structure: Option<f64>,
    pub risk_total_score: Option<f64>,
    pub risk_volatility: Option<f64>,
}

/// A single holding (constituent) of an ETF composite.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct EtfGlobalConstituent {
    pub asset_class: Option<String>,
    pub composite_ticker: Option<String>,
    pub constituent_name: Option<String>,
    pub constituent_ticker: Option<String>,
    pub country_of_exchange: Option<String>,
    pub currency_traded: Option<String>,
    pub effective_date: Option<String>,
    pub exchange: Option<String>,
    pub figi: Option<String>,
    pub isin: Option<String>,
    pub market_value: Option<f64>,
    pub processed_date: Option<String>,
    pub security_type: Option<String>,
    pub sedol: Option<String>,
    pub shares_held: Option<f64>,
    pub us_code: Option<String>,
    pub weight: Option<f64>,
}

/// Daily fund flow, NAV and shares outstanding for an ETF composite.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct EtfGlobalFundFlow {
    pub composite_ticker: Option<String>,
    pub effective_date: Option<String>,
    pub fund_flow: Option<f64>,
    pub nav: Option<f64>,
    pub processed_date: Option<String>,
    pub shares_outstanding: Option<f64>,
}

/// Profile, fee and exposure data for an ETF composite.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct EtfGlobalProfile {
    pub administrator: Option<String>,
    pub advisor: Option<String>,
    pub asset_class: Option<String>,
    pub aum: Option<f64>,
    pub avg_daily_trading_volume: Option<f64>,
    pub bid_ask_spread: Option<f64>,
    pub call_volume: Option<f64>,
    pub category: Option<String>,
    pub composite_ticker: Option<String>,
    pub coupon_exposure: Option<std::collections::HashMap<String, f64>>,
    pub creation_fee: Option<f64>,
    pub creation_unit_size: Option<f64>,
    pub currency_exposure: Option<std::collections::HashMap<String, f64>>,
    pub custodian: Option<String>,
    pub description: Option<String>,
    pub development_class: Option<String>,
    pub discount_premium: Option<f64>,
    pub distribution_frequency: Option<String>,
    pub distributor: Option<String>,
    pub effective_date: Option<String>,
    pub fee_waivers: Option<f64>,
    pub fiscal_year_end: Option<String>,
    pub focus: Option<String>,
    pub futures_commission_merchant: Option<String>,
    pub geographic_exposure: Option<std::collections::HashMap<String, f64>>,
    pub inception_date: Option<String>,
    pub industry_exposure: Option<std::collections::HashMap<String, f64>>,
    pub industry_group_exposure: Option<std::collections::HashMap<String, f64>>,
    pub issuer: Option<String>,
    pub lead_market_maker: Option<String>,
    pub leverage_style: Option<String>,
    pub levered_amount: Option<f64>,
    pub listing_exchange: Option<String>,
    pub management_classification: Option<String>,
    pub management_fee: Option<f64>,
    pub maturity_exposure: Option<std::collections::HashMap<String, f64>>,
    pub net_expenses: Option<f64>,
    pub num_holdings: Option<f64>,
    pub options_available: Option<i64>,
    pub options_volume: Option<f64>,
    pub other_expenses: Option<f64>,
    pub portfolio_manager: Option<String>,
    pub primary_benchmark: Option<String>,
    pub processed_date: Option<String>,
    pub product_type: Option<String>,
    pub put_call_ratio: Option<f64>,
    pub put_volume: Option<f64>,
    pub region: Option<String>,
    pub sector_exposure: Option<std::collections::HashMap<String, f64>>,
    pub short_interest: Option<f64>,
    pub subadvisor: Option<String>,
    pub subindustry_exposure: Option<std::collections::HashMap<String, f64>>,
    pub tax_classification: Option<String>,
    pub total_expenses: Option<f64>,
    pub transfer_agent: Option<String>,
    pub trustee: Option<String>,
}

/// Classification and strategy taxonomy for an ETF composite.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct EtfGlobalTaxonomy {
    pub asset_class: Option<String>,
    pub category: Option<String>,
    pub composite_ticker: Option<String>,
    pub country: Option<String>,
    pub credit_quality_rating: Option<String>,
    pub description: Option<String>,
    pub development_class: Option<String>,
    pub duration: Option<String>,
    pub effective_date: Option<String>,
    pub esg: Option<String>,
    pub exposure_mechanism: Option<String>,
    pub factor: Option<String>,
    pub focus: Option<String>,
    pub hedge_reset: Option<String>,
    pub holdings_disclosure_frequency: Option<String>,
    pub inception_date: Option<String>,
    pub isin: Option<String>,
    pub issuer: Option<String>,
    pub leverage_reset: Option<String>,
    pub leverage_style: Option<String>,
    pub levered_amount: Option<f64>,
    pub management_classification: Option<String>,
    pub management_style: Option<String>,
    pub maturity: Option<String>,
    pub objective: Option<String>,
    pub primary_benchmark: Option<String>,
    pub processed_date: Option<String>,
    pub product_type: Option<String>,
    pub rebalance_frequency: Option<String>,
    pub reconstitution_frequency: Option<String>,
    pub region: Option<String>,
    pub secondary_objective: Option<String>,
    pub selection_methodology: Option<String>,
    pub selection_universe: Option<String>,
    pub strategic_focus: Option<String>,
    pub targeted_focus: Option<String>,
    pub tax_classification: Option<String>,
    pub us_code: Option<String>,
    pub weighting_methodology: Option<String>,
}
